version: '3'
services:
  registration-service:
    build:
      context: ./registration-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - mongo

  listener-service:
    build:
      context: ./listener-service
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
